openapi: 3.2.0
info:
  title: GP Connect Prescriptions Management FHIR Task API
  version: Computed and injected at build time by `scripts/set_version.py`
  description: '## Overview


    !GP Connect Patient Facing Prescriptions Management API Overview


    Use this API to manage a patient''s prescriptions as held by their GP practice.'
  contact:
    name: gp-connect/patient-facing/prescriptions-management-fhir/FHIR/R4 API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
servers:
- url: https://sandbox.api.service.nhs.uk/gp-connect/patient-facing/prescriptions-management-fhir/FHIR/R4
  description: Sandbox environment.
- url: https://int.api.service.nhs.uk/gp-connect/patient-facing/prescriptions-management-fhir/FHIR/R4
  description: Integration test environment.
- url: https://api.service.nhs.uk/gp-connect/patient-facing/prescriptions-management-fhir/FHIR/R4
  description: Production environment.
tags:
- name: Task
paths:
  /Task:
    post:
      operationId: post-task
      summary: Request a repeat prescription
      description: '## Overview


        Use this end point to create a request for a repeat prescription.


        The same end point can be used to request a prescription to a one off pharmacy nomination - the ODS code is set in Task.input using code preferred-performer.


        For this, send a Task with a focus of a prior MedicationRequest which has an intent of plan. This can be obtain by using the GET `/MedicationRequest/Patient/` endpoint within this API.


        ## Use cases

        Use cases covered by this endpoint include:


        * request the next issue of a repeat prescription


        * request the next issue of a repeat prescription to a one off pharmacy nomination


        * request


        ## Request workflow

        When a request is made it is added to the GP system''s workflow and processed at some point in the future.

        At this point the status of the Task resource will be updated as it passes through the GP system''s workflow.

        If a request is rejected the statusReason element of the Task resource will be populated with the reason to be displayed to the patient.'
      parameters:
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      requestBody:
        required: true
        description: Successful Request.
        content:
          application/fhir+json:
            schema:
              type: object
              description: 'Information surrounding how the Task resource is populated can be found [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/FHIR-Assets/All-Assets/Profiles/UKCore-Task?version=0.1.1-private-beta).

                '
            example:
              resourceType: Task
              meta:
                profile:
                - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
              identifier:
              - system: https://tools.ietf.org/html/rfc4122
                value: ce3354f5-98c2-43ad-95bd-a6df1c5ed169
              status: requested
              intent: order
              code:
                coding:
                - system: http://snomed.info/sct
                  code: '103742009'
                  display: Renewal of prescription
              focus:
                reference: MedicationRequest/b269d1d7-1acf-47bb-8b3c-e38b583d9a07
              for:
                reference: Patient/9000000009
                identifier:
                  system: https://fhir.nhs.uk/Id/nhs-number
                  value: '9000000009'
                display: Jane Smith
              authoredOn: 2022-10-13 09:20:27+00:00
              lastModified: 2022-10-13 09:20:27+00:00
              requester:
                reference: Patient/9000000009
                identifier:
                  system: https://fhir.nhs.uk/Id/nhs-number
                  value: '9000000009'
                display: Jane Smith
              note:
              - authorString: Patient
                text: ran out of previous prescription
              input:
              - type:
                  coding:
                  - system: https://fhir.nhs.uk/England/CodeSystem/England-PFSPrescriptionOrderingParameter
                    code: preferred-performer
                    display: Preferred performer
                valueIdentifier:
                  system: https://fhir.nhs.uk/Id/ods-organization-code
                  value: FLM49
      responses:
        '201':
          description: A successful response to the POST request will return the created object now populated with an id.
          content:
            application/fhir+json:
              schema:
                type: object
              examples:
                operation-outcome-success:
                  value:
                    resourceType: Task
                    id: 7c747c6e-15c8-4b2f-8aa0-441f2ef703d6
                    meta:
                      profile:
                      - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                    identifier:
                    - system: https://tools.ietf.org/html/rfc4122
                      value: ce3354f5-98c2-43ad-95bd-a6df1c5ed169
                    status: requested
                    intent: order
                    code:
                      coding:
                      - system: http://snomed.info/sct
                        code: '103742009'
                        display: Renewal of prescription
                    focus:
                      reference: MedicationRequest/b269d1d7-1acf-47bb-8b3c-e38b583d9a07
                    for:
                      reference: Patient/9000000009
                      identifier:
                        system: https://fhir.nhs.uk/Id/nhs-number
                        value: '9000000009'
                      display: Jane Smith
                    authoredOn: 2022-10-13 09:20:27+00:00
                    lastModified: 2022-10-13 09:20:27+00:00
                    requester:
                      reference: Patient/9000000009
                      identifier:
                        system: https://fhir.nhs.uk/Id/nhs-number
                        value: '9000000009'
                      display: Jane Smith
                    note:
                    - authorString: Patient
                      text: ran out of previous prescription
                    input:
                    - type:
                        coding:
                        - system: https://fhir.nhs.uk/England/CodeSystem/England-PFSPrescriptionOrderingParameter
                          code: preferred-performer
                          display: Preferred performer
                      valueIdentifier:
                        system: https://fhir.nhs.uk/Id/ods-organization-code
                        value: FLM49
        4XX:
          description: "An error occured as follows:\n\n\n| HTTP Status | Spine error code      | Description\n|-------------|-----------------------|------------\n| 400         | BAD_REQUEST           | X-Request-ID is not present\n| 403         | ACCESS_DENIED         | Access denied, the patient logged in does not have the correct access level\n| 409         | DUPLICATE_REJECTED\t  | Create would lead to creation of a duplicate resource\n| 422         | INVALID_RESOURCE      | Task resource failed validation (any incorrect values)\n| 422         | INVALID_RESOURCE      | Task missing required focus reference\n| 422         | REFERENCE_NOT_FOUND   | focus reference to MedicationRequest not valid\n| 422         | REFERENCE_NOT_FOUND   | requester reference to Patient not valid\n| 422         | REFERENCE_NOT_FOUND   | for reference to Patient not valid\n"
          content:
            application/fhir+json:
              schema:
                type: object
                description: Link to UKCore-OperationOutcome resource population guidance [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/FHIR-Assets/All-Assets/Profiles/UKCore-OperationOutcome?version=0.1.1-private-beta).
              examples:
                example:
                  value:
                    resourceType: OperationOutcome
                    meta:
                      profile:
                      - https://fhir.hl7.org.uk/StructureDefinition/UKCore-OperationOutcome
                    issue:
                    - severity: error
                      code: business-rule
                      details:
                        coding:
                        - system: https://fhir.nhs.uk/R4/ValueSet/Spine-ErrorOrWarningCode-1
                          code: CONFLICTING_VALUES
                          display: Mismatched prescribed item to quantity
      tags:
      - Task
    get:
      operationId: get-task
      summary: Get requested prescription reorders
      description: '## Overview


        Use this end point to check the status of past and current prescription reorder requests.


        If a Patient identifier is provided past and present requests will be returned for the patient inside as multiple Task rescources inside a Bundle resource.


        If just the id of a specific request is passed a singular Task resource will be returned inside a Bundle resource.


        If the prescription request is then sent to EPS to be fulfilled the EPS id of the new MedicationRequest must be included in the output element of the Task resource.


        You must provide at least one of the following parameters:


        * id


        * patient

        ## Use cases

        Use cases covered by this endpoint include:


        * present inflight prescription requests to the Patient


        * allow the patient to check the status of a specific request


        * obtain the EPS id of a prescription reorder request that has been sent to be dispensed


        * obtain a list of requests to enable the patient to send a cancellation'
      parameters:
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - in: query
        name: patient
        description: 'The NHS number of the patient whose requests you are searching for

          '
        required: true
        schema:
          type: string
          example: '9912003489'
      - in: query
        name: _include
        description: 'Task:focus:MedicationRequest - Include MedicationRequest resources referenced within the returned Task resources, further information around the benefits and using this parameter can be found [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/Build/How-to-determine-the-medication-the-request-belongs-to?version=0.1.1-private-beta).

          '
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - Task:focus:MedicationRequest
      - in: query
        name: id
        description: 'The id of the Task itself

          '
        required: false
        schema:
          type: string
          example: dad85fcc-d3a0-4806-886a-a573bd48ad2c
      - in: query
        name: status
        description: 'The type of status to search: you can find valid values [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/FHIR-Assets/All-Assets/Profiles/UKCore-Task?version=0.1.1-private-beta#status).

          '
        required: false
        schema:
          type: string
          example: requested
      - in: query
        name: authored-on
        description: 'Date the prescription was requested, format: <eq|ge|le>YYYY-MM-DD. To use a range use authored-on=geYYYY-MM-DD&authored-on=leYYYY-MM-DD

          '
        required: false
        schema:
          type: string
        examples:
          exact date:
            value: eq2010-10-22
            description: Exact match date
          greater than or equals:
            value: ge2022-01-15
            description: Greater than or equals which matches 2022-01-15 or 2022-01-16
          less than or equals:
            value: le2022-01-15
            description: Less than or equals which matches 2022-01-15 or 2022-01-14
      responses:
        '200':
          description: Successful query
          content:
            application/fhir+json:
              schema:
                type: object
                description: Information surrounding how the Task resource is populated can be found [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/FHIR-Assets/All-Assets/Profiles/UKCore-Task?version=0.1.1-private-beta).
              examples:
                bundle:
                  description: Successful request to view requests for prescriptions when a patient identifier is passed.
                  value:
                    resourceType: Bundle
                    id: a96bb563-c86b-4021-903e-5917b927c386
                    identifier:
                      system: https://tools.ietf.org/html/rfc4122
                      value: a3294018-6c63-4556-8797-f782d1c95480
                    type: searchset
                    entry:
                    - fullUrl: 20885a31-acf0-42d5-bd5b-85c23f7a32fd
                      resource:
                        resourceType: Task
                        id: aef77afb-7e3c-427a-8657-2c427f71a271
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 725ca1bd-2860-4476-8802-8d035d802e7f
                        status: requested
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: 2022-11-23 20:20:27+07:00
                        lastModified: 2022-11-23 20:20:27+07:00
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        note:
                        - authorString: Patient
                          text: Ran out of previous prescription
                    - fullUrl: 15c5ee13-73cf-45f8-a1f1-a7de3e10dae6
                      resource:
                        resourceType: Task
                        id: b395d57e-5d6c-4d2c-b590-fe2f2d708458
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 725ca1bd-2860-4476-8802-8d035d802e7f
                        status: rejected
                        statusReason:
                          text: No longer suitable, please contact GP to organise an appointment
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: 2022-08-14 07:20:23+07:00
                        lastModified: 2022-08-14 11:40:47+07:00
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                    - fullUrl: 561d0bfa-a937-4d91-81ab-abe65bca2d95
                      resource:
                        resourceType: Task
                        id: 84722efb-95b0-4769-921a-eda53382b320
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 2270b136-7a4c-491e-8bf1-624b5c4f20b7
                        status: in-progress
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: 2022-10-13 16:20:27+07:00
                        lastModified: 2022-10-15 11:28:13+07:00
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                completed and sent to EPS:
                  description: Completed prescription reorder request when sent to EPS.
                  value:
                    resourceType: Bundle
                    id: a96bb563-c86b-4021-903e-5917b927c386
                    identifier:
                      system: https://tools.ietf.org/html/rfc4122
                      value: a3294018-6c63-4556-8797-f782d1c95480
                    type: searchset
                    entry:
                    - fullUrl: 20885a31-acf0-42d5-bd5b-85c23f7a32fd
                      resource:
                        resourceType: Task
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 30d65c8e-98e8-4806-b6a6-fpwjfkhs729
                        status: completed
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/b269d1d7-1acf-47bb-8b3c-e38b583d9a07
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: '2023-01-10T09:20:27.000Z'
                        lastModified: '2023-01-20T10:20:24.000Z'
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        output:
                        - type:
                            coding:
                            - system: https://fhir.nhs.uk/England/CodeSystem/England-PFSPrescriptionOrderingParameter
                              code: sent-to-eps
                              display: Sent to EPS
                          valueIdentifier:
                            system: https://fhir.nhs.uk/Id/prescription-order-item-number
                            value: 4857b9d3-b714-44b9-9e67-3df67275b785
                include Medication Requests:
                  description: Successful request to view requests for prescriptions when a patient identifier is passed and _include parameters are used to return the referenced medication requests.
                  value:
                    resourceType: Bundle
                    id: a96bb563-c86b-4021-903e-5917b927c386
                    identifier:
                      system: https://tools.ietf.org/html/rfc4122
                      value: a3294018-6c63-4556-8797-f782d1c95480
                    type: searchset
                    entry:
                    - fullUrl: 20885a31-acf0-42d5-bd5b-85c23f7a32fd
                      resource:
                        resourceType: MedicationRequest
                        id: 06c7d0e2-1022-4e47-ac55-f6463d701a4f
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-MedicationRequest
                        extension:
                        - url: https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationRepeatInformation
                          extension:
                          - url: numberOfPrescriptionsIssued
                            valueUnsignedInt: 1
                          - url: authorisationExpiryDate
                            valueDateTime: '2023-09-10T19:00:00.000Z'
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 42b4a841-9d69-4d13-bf91-ee5882e85765
                        status: active
                        intent: plan
                        category:
                        - coding:
                          - system: http://terminology.hl7.or/CodeSystem/medicationrequest-category
                            code: community
                            display: Community
                        medicationCodeableConcept:
                          coding:
                          - system: https://dmd.nhs.uk
                            code: '3113111000001106'
                            display: Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        subject:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        requester:
                          reference: PractitionerRole/ed313d93-f470-420f-ae4e-2b7eb91d3f45
                          display: Dr Jane Smith
                        groupIdentifier:
                          system: https://fhir.nhs.uk/Id/prescription-order-number
                          value: PDI12E-Y765908-4FF3LQ
                        courseOfTherapyType:
                          coding:
                          - system: http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy
                            code: continuous
                            display: Continuous long term therapy
                        authoredOn: '2022-10-13T16:20:27+07:00'
                        substitution:
                          allowedBoolean: false
                        dosageInstruction:
                        - text: One to two puffs to be inhaled as needed
                          method:
                            coding:
                            - system: http://snomed.info/sct
                              code: '420652005'
                              display: Until gone
                        dispenseRequest:
                          numberOfRepeatsAllowed: 6
                          quantity:
                            value: 1
                            unit: inhaler
                            system: http://snomed.info/sct
                            code: '334980009'
                          expectedSupplyDuration:
                            value: 28
                            unit: days
                            system: http://unitsofmeasure.org
                            code: d
                    - fullUrl: 20885a31-acf0-42d5-bd5b-85c23f7a32fd
                      resource:
                        resourceType: Task
                        id: aef77afb-7e3c-427a-8657-2c427f71a271
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 725ca1bd-2860-4476-8802-8d035d802e7f
                        status: requested
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: '2022-11-23T20:20:27+07:00'
                        lastModified: '2022-11-23T20:20:27+07:00'
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        note:
                        - authorString: Patient
                          text: Ran out of previous prescription
                    - fullUrl: 15c5ee13-73cf-45f8-a1f1-a7de3e10dae6
                      resource:
                        resourceType: Task
                        id: fjugkd8281-4tngn-j4fn-8657-2knrkfjrgu
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 725ca1bd-2860-4476-8802-8d035d802e7f
                        status: rejected
                        statusReason:
                          text: No longer suitable, please contact GP to organise an appointment
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: '2022-08-14T07:20:23+07:00'
                        lastModified: '2022-08-14T11:40:47+07:00'
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                    - fullUrl: 561d0bfa-a937-4d91-81ab-abe65bca2d95
                      resource:
                        resourceType: Task
                        id: 84722efb-95b0-4769-921a-eda53382b320
                        meta:
                          profile:
                          - https://fhir.hl7.org.uk/StructureDefinition/UKCore-Task
                        identifier:
                        - system: https://tools.ietf.org/html/rfc4122
                          value: 2270b136-7a4c-491e-8bf1-624b5c4f20b7
                        status: in-progress
                        intent: order
                        code:
                          coding:
                          - system: http://snomed.info/sct
                            code: '103742009'
                            display: Renewal of prescription
                        focus:
                          reference: MedicationRequest/06c7d0e2-1022-4e47-ac55-f6463d701a4f
                          display: Repeat prescription for Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)
                        for:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
                        authoredOn: '2022-10-13T16:20:27+07:00'
                        lastModified: '2022-10-15T11:28:13+07:00'
                        requester:
                          reference: Patient/9000000009
                          identifier:
                            system: https://fhir.nhs.uk/Id/nhs-number
                            value: '9000000009'
                          display: Jane Smith
        4XX:
          description: "An error occured as follows:\n\n\n| HTTP Status | Spine error code   | Description\n|-------------|--------------------|------------\n| 400         | BAD_REQUEST        | X-Request-ID is not present            \n| 403         | ACCESS_DENIED      | Access denied, the patient logged in does not have the correct access level\n| 404         | RESOURCE_NOT_FOUND | The request is for a Task that doesn't exist\n| 404         | PATIENT_NOT_FOUND  | The request is for a Patient that doesn't exist\n| 422         | INVALID_PARAMETER  | The Task id supplied is invalid\n| 422         | INVALID PARAMERER  | Date is invalid \n"
          content:
            application/fhir+json:
              schema:
                type: object
                description: Link to UKCore-OperationOutcome resource population guidance [here](https://simplifier.net/guide/gp-connect--patient-facing-services--prescriptions/Home/FHIR-Assets/All-Assets/Profiles/UKCore-OperationOutcome?version=0.1.1-private-beta).
              examples:
                example:
                  value:
                    resourceType: OperationOutcome
                    meta:
                      profile:
                      - https://fhir.hl7.org.uk/StructureDefinition/UKCore-OperationOutcome
                    issue:
                    - severity: error
                      code: business-rule
                      details:
                        coding:
                        - system: https://fhir.nhs.uk/R4/ValueSet/Spine-ErrorOrWarningCode-1
                          code: CONFLICTING_VALUES
                          display: Mismatched prescribed item to quantity
      tags:
      - Task
components:
  parameters:
    RequestID:
      in: header
      name: X-Request-ID
      required: true
      description: 'A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.

        Must be a universally unique identifier (UUID) (ideally version 4).


        Mirrored back in a response header.


        If you re-send a failed request, use the same value in this header.


        Required in all environments except sandbox.

        '
      schema:
        type: string
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
    BearerAuthorization:
      in: header
      name: Authorization
      description: 'An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).

        Required in all environments except sandbox.

        '
      required: true
      schema:
        type: string
        format: ^Bearer\ [[:ascii:]]+$
        example: Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: 'An optional ID which you can use to track transactions across multiple systems. It can have any value, but we recommend avoiding `.` characters.

        Mirrored back in a response header.

        '
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
x-spec-publication:
  operation-order:
  - operations:
    - method: GET
      path: /Patient/{id}/MedicationRequest
    - method: POST
      path: /Task
    - method: GET
      path: /Task
