openapi: 3.0.0
info:
  title: gp-connect-access-record-structured-fhir Appointment Documents API
  version: Computed and injected at build time by `scripts/set_version.py`
  description: "## Overview\nUse this API to access structured information from a patient's registered GP practice record. Structured information is patient data in a coded format that a consuming system can import and process.\n\nThe API accesses GP principal supplier systems, provides a consistent interface and data model, and is brokered through [Spine](https://digital.nhs.uk/services/spine). Refer to [Spine terminology](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/spine-terminology), used throughout these pages, for further details.\n\n![GP Connect Ecosystem Overview](https://raw.githubusercontent.com/NHSDigital/gp-connect-access-record-structured-fhir/master/specification/images/gpconnect-ecosystem.svg)\n\nYou can retrieve data from GP practice records for the following areas:\n\n- medications\n- allergies\n\nData is available for the following clinical areas:\n\n- immunizations\n- consultations\n- problems\n- investigations\n- outbound referrals\n- diary entries\n- uncategorised data (other clinically coded items that are present in the record)\n\nThese clinical areas are still in development; there is enough data to test, but it is subject to change as GP systems suppliers go through the development process.\n\nIt does not include:\n\n- extended demographics information - for example, about carers\n- flags and alerts\n- templates\n- test requests\n\nCommon use cases include:\n\n- access GP medications on admission to secondary care, reducing transcription errors\n- active checking of a patient's prescription in unscheduled care\n- out-of-hours GP accesses patient's medications, allergies and problems\n- midwife views patient record before visiting a patient\n- community cardiac nurse accesses GP record before visiting a patient\n\n\nFor more details, see the [GP Connect Access Record: Structured specification](https://developer.nhs.uk/apis/gpconnect-1-5-1/accessrecord_structured.html), and for a description of terms and standards used in this guide, please see the [General API Guidance page](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/general-api-guidance).\n\nYou cannot currently use this API to:\n\n- create patient-facing views of a medical record\n- create reports for secondary use, such as care planning\n- write back to the GP record\n\n\n### Retrieving documents\n\nTo retrieve documents from a patient's registered GP practice, use [GP Connect Access Document - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-document-fhir). After you've found the relevant document references within Access Record returns, use GP Connect Access Document to retrieve the documents. All documents can be requested separately.\n\n\n## Who can use this API\nThis API can be used by developers of clinical systems that support clinicians delivering direct care.\n\nBefore you start development, read the [GP Connect API 1.5.1-beta](https://developer.nhs.uk/apis/gpconnect-1-5-1/) specification and the prerequisites listed below.  \n\nBecome an API consumer\nIf you're planning on consuming data using GP Connect APIs then you're a consumer system.\n\nBecome an API provider\nIf you're planning on providing data using GP Connect APIs then you're a provider system.\n\n### Prerequisites\n#### Technical\nThe technical prerequisites are as follows:\n\n- you must have access to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network)\n- you must be [Personal Demographics Service (PDS)](https://digital.nhs.uk/Demographics)-compliant or capable of performing a PDS search via NHS Digital or a third-party provider\n#### Information governance (IG)\nThe IG prerequisites are as follows:\n\n- your organisation must be compliant with the [GP Connect Direct Care API Information Governance Model](https://github.com/nhsconnect/gpc-consumer-support/wiki/Information-Governance-(IG))\n- you must manage access to your system locally using local role-based access control (RBAC) (this does not need to be compliant with the national RBAC model and GP Connect products do not require smartcards to control access, though they can be used if already implemented)\n\n- the GP Connect APIs are for direct care purposes for NHS patients in England\n### Clinical safety\nThe clinical safety prerequisites are as follows:\n\n- you must have a clinical safety officer (CSO) who is responsible for [DCB0129](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0129-clinical-risk-management-its-application-in-the-manufacture-of-health-it-systems) and, if necessary, [DCB0160](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0160-clinical-risk-management-its-application-in-the-deployment-and-use-of-health-it-systems) (for more on clinical risk management, visit [Clinical risk management standards](https://digital.nhs.uk/services/clinical-safety/clinical-risk-management-standards))\nIf you are confident that you can meet the prerequisites, please express an interest with the GP Connect team (see 'Onboarding' below).\n\n## Related APIs\nThe following APIs are also related to this API:\n\n- GP Connect Access Document - FHIR API - use this API to retrieve unstructured documents from a patient's GP practice record\n- Personal Demographics Service - FHIR API  - use this API to search for patients, retrieve patients by NHS number and update patients\n- Personal Demographics Service - HL7 V3 API  - use this if you want to use functions that are not yet available on the FHIR API\n- Spine Directory Service (SDS) - FHIR API  - access accredited system information and messaging endpoint details\n\n## Integration with Spine\nFor guidance on how to integrate with the Spine systems required to use this API, please see the [integrate with spine](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/spine-integration) page.\n\nFor guidance on querying and using the Spine Directory Service (SDS) [please see the Spine Directory Service page](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/spine-directory-service).\n## API status and roadmap\nThe current working version is 1.5.1. The API status is:\n\n- in production (out of beta) for medications and allergies - there will be no breaking changes\n- in production, beta for other aspects of the clinical record - there might be breaking changes, but we will let you know in advance\nIt may not be fully supported by all providing systems. See [GP Connect supplier progress](https://digital.nhs.uk/services/gp-connect/supplier-progress) for details of provider rollout.\n\nThe previous version ([1.5.0](https://developer.nhs.uk/apis/gpconnect-1-5-0/)) does not include the ability to access deceased patients' documents, but is available for system suppliers who have started to develop against it.\n\nRoadmap\n\nThe next planned version is [1.6.0](https://developer.nhs.uk/apis/gpconnect-1-6-0/), which is currently [in production, beta](http://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses). The 1.6.0 specification contains the full scope of 1.5.1, but additionally it introduces a new message to support GP2GP transactions. It is important to understand that the GP2GP transactions do not affect the consumer build. 1.6.0 will be backward compatible with the 1.5.1 specification.\n## Service level\nThis API is a silver service, meaning it is operational 24 hours a day, 365 days a year but only supported during business hours (8am to 6pm), Monday to Friday excluding bank holidays.\n\nFor more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).\n## Technology\nThis is a synchronous API. It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange. Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 3. \n\nIt uses a FHIR Operation that requires you to make a HTTP POST of a FHIR Parameters resource to the provider endpoint. The resource contains parameters that correspond to the requested clinical information - for example, medications, allergies or problems.\n\nWe use this approach instead of a resource-based RESTful API in the interests of clinical safety. The provider system constructs a response that contains all clinical information relating to the request to ensure that the clinical information is interpreted safely.\n\n\n## Network access\nYou can access this API via the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).\n\nThe API is not currently available over the internet, but we plan to enable public internet access in the future.\n\nFor more details, see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).\n## Security and authorisation\n### Security\nAccess to the GP Connect APIs is controlled and protected by the [Spine Secure Proxy (SSP)](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#spine-security-proxy-ssp-), a forward HTTP proxy.\n\nIt provides a single security point for both authentication and authorisation for consuming systems. Additional responsibilities include auditing of requests, checking data sharing agreements and transaction logging, and its use and examples are described at the [Spine Secure Proxy page](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/spine-secure-proxy).\n\nFor a breakdown of cross-organisation audit and provenance, please see the related page [here](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/cross-organisation-audit-and-provenance).\n\nAll HTTP communications are secured using TLS MA. This includes both legs of the request, from consumer system to the proxy and then from the proxy to provider system.\n\n### Authorisation\nAuthorisation takes place in two locations: \n\n- the consumer system\n- the SSP\nThe consumer system must have local RBAC in place and restrict GP Connect APIs to authorised users. With each request, a JSON Web Token (JWT) must be included with the following information:\n\n- details of users, including role\n- where smartcards are used in the consumer system, including SDS user and role IDs\n- details of the consumer system\n- details of the consumer's organisation, including ODS code\nThe information in the JWT is retained for audit purposes.\n\nProvider systems:\n- SHALL only accept connections from the [Spine Secure Proxy](https://developer.nhs.uk/apis/gpconnect-1-5-0/integration_spine_secure_proxy.html) (SSP)\n- SHALL authenticate the SSP prior to responding to any requests using its [client certificate](https://developer.nhs.uk/apis/gpconnect-1-5-0/development_api_security_guidance.html#client-certificates-tlsma)\n- SHALL only accept encrypted connections and drop connection attempts presented over insecure protocols\n- SHALL only accept requests for its allocated address space identifier (ASID), as specified by the Ssp-To header on its matching endpoint URL\n- SHALL check that the Ssp-InteractionID value is consistent with the endpoint being requested\n- SHALL check for the presence of all [SSP headers](https://developer.nhs.uk/apis/spine-core-1-0/ssp_implementation_guide.html#consumer)\n- SHALL check that an [authorization bearer token](https://developer.nhs.uk/apis/gpconnect-1-5-0/integration_cross_organisation_audit_and_provenance.html#json-web-tokens-jwt) is present and correctly formed\n- MAY authorise access to API endpoints through examining acceptable values in the JSON Web Tokens (JWT) requested_scope claim\n- SHALL risk-manage the security of the endpoints of the Transport Layer Security (TLS) communications, so as to prevent inappropriate risks (for example, audit logging of the GET parameters into an unprotected audit log)\n\nProvider systems should support only the following ciphers, ordered by preference (that is, the first item being the most preferred):\n- AESGCM+EECDH\n- AESGCM+EDH\n- AES256+EECDH\n- AES256+EDH\n\nThe SSP checks data-sharing agreements to ensure that the consumer system is authorised to communicate with the provider system.\n\nMore details of both the ciphers and TLS approach, as well as headers and certificates, can be found on the [Security page](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/security).\n\n## Error Handling\nA full breakdown of errors, including examples, can be found on the [Error Handling page](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/error-handling).\n\n## Environments and testing\n| Environment\t                 | URL |\n| -----------                  | --- |\n| Internet-facing demonstrator | \t[https://orange.testlab.nhs.uk/](https://orange.testlab.nhs.uk/) |\n| OpenTest environment\t       | [https://orange.testlab.nhs.uk/opentest.html](https://orange.testlab.nhs.uk/opentest.html) |\n| Integration                  |  (INT)\tProvided during onboarding process |\nWe have 2 testing streams:\n\n- clinical testing\n- technical testing\nEach stream is complicated in its own right and we've designed them to run in parallel to help you to work with us more easily and to consider your system design in a holistic way, rather than having to complete one stream before the other.\n\n### Clinical testing\nThe aim of clinical testing is to ensure the safe interoperability of information exported from GP systems and then processed or displayed in a consuming system. \n\nTo help you test that your consuming system is clinically safe, we have created the following resources:\n\n- a patient record or, for some more complex areas, 2 records that can be requested from the GP Connect demonstrator\n- a description of each of the data items, what it is intending to test and the hazards that it is intended to mitigate\n- notes and guidance about each clinical area that describe how to process and display the data that it contains in a safe way\nSee [Clinical test data](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-record-structured-fhir/clinical-test-data).\n\n### Technical testing\nThe purpose of technical testing is to help you assure the messaging capability of your system via the Spine with GP Connect provider FHIR endpoints. It ensures the consumer requests conform to FHIR standards as per the specification. In addition, it maintains the integrity of the data displayed to the user and assures pertinent functional requirements. It does not assure the message payload, which is covered in clinical assurance.\n\nAn automated provider test harness has been made publicly available to allow standardised testing of the FHIR® APIs prior to any formal assurance activities being undertaken. This approach aims to streamline the end-to-end assurance process by ensuring that a common baseline level of technical conformance has been achieved and, thus, fewer issues are surfaced during formal assurance.\n\nDownload the [GP Connect automated test suite for API providers](https://github.com/nhsconnect/gpconnect-provider-testing) to help validate the technical conformance of your provider API implementation.\n\nSee [Consumer Supplier Test Assurance for achieving Technical Conformance](https://github.com/nhsconnect/gpc-consumer-support/wiki/Document-library#consumer-supplier-test-assurance-for-achieving-technical-conformance) (PDF) for full details of the technical conformance process and relevant artefacts.\n## Onboarding\nExpressing an interest\nIf you meet the prerequisites and have a product that can integrate with GP Connect, you should express an interest with us by submitting a use case.\n\nThe main purpose of the use case is to help us understand how you plan to use GP Connect APIs and the business issue you are looking to address. You should email your use case to the [GP Connect team](mailto:gpconnect@nhs.net).\n\nYour use case should include the following information as a minimum:\n\n- the business problem you are intending to solve using GP Connect\n- how GP Connect will be used in practice to benefit patients and staff\n- which of the GP Connect products you will use to benefit patients and staff\n- any end-user organisations you are currently working with\n- who your clinical safety officer is and, where available, your clinical risk management process documentation\nOnce we receive your use case, we'll respond within 14 days.\n\nConsumer assurance process\nOn approval of a use case, we will support you through the assurance process through to go live. We will discuss the [assurance process](https://github.com/nhsconnect/gpc-consumer-support/wiki/Assurance-Process-Overview) and artefacts with you to help you understand the requirements.\n\n![Access Record Structured Consumer Assurance Process](https://raw.githubusercontent.com/NHSDigital/gp-connect-access-record-structured-fhir/master/specification/images/access-record-structured-consumer-assurance-process.svg)\n\nStart your development work within 6 months of use case approval. If you miss this date, a review or new submission of the use case will be required. Changes or additional development will also require a review or new use case submission. For full details of the technical conformance process, see [GP Connect Consumer Supplier Test Assurance for achieving Technical Conformance](https://github.com/nhsconnect/gpc-consumer-support/wiki/Document-library#consumer-supplier-test-assurance-for-achieving-technical-conformance) (PDF).\n\nClinical assurance process\nWe are here to support you to develop clinically safe systems in line with your responsibility to achieve the relevant [DCB0129](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0129-clinical-risk-management-its-application-in-the-manufacture-of-health-it-systems) or [DCB0160](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0160-clinical-risk-management-its-application-in-the-deployment-and-use-of-health-it-systems) clinical safety standards. \n\n![Access Record Structured Clinicals Assurance Process](https://raw.githubusercontent.com/NHSDigital/gp-connect-access-record-structured-fhir/master/specification/images/gpc2-structured-consumer-clinical-assurance-process.svg)\n\nThe three stages of the clinical assurance process for GP Connect Access Record: Structured consumers\n\nWe host a series of meetings to help you develop clinically safe systems:\n\n- initial meeting\n- clinical safety process readiness review meeting\n- clinical evaluation of readiness for deployment meeting\nFor more information, see [Clinical assurance process details](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-record-structured-fhir/clinical-assurance-process-details).\n\n## Interactions\nFor a full list of interactions for this API, see [GP Connect Interaction IDs](https://digital.nhs.uk/developer/api-catalogue/gp-connect-general-pages/interaction-ids), which contains Access Record: Structured.\n\nFor details on the general structure of the interactions, see [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir).\n  \n## Additional guidance: Clinical safety and hazard log\n### Clinical safety approach\nYour organisation must have a clinical safety officer. Information standards underpin national healthcare initiatives from the Department of Health, NHS England, the Care Quality Commission, and other national health organisations. They provide the mechanism for introducing requirements to which the NHS, those with whom it commissions services and its IT system suppliers, must conform.\n\nThe following two standards relating to clinical safety are accepted for publication under section 250 of the Health and Social Care Act 2012 by the Data Coordination Board (DCB). In line with current DCB practice, each standard comprises:\n\n- a specification, which defines the requirements and conformance criteria to be met by the user of the standard - how these requirements are met is the responsibility of the user\n- implementation guidance, which provides an interpretation of the requirements and, where appropriate, defines possible approaches to achieving them\nCompliance with [DCB0129](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0129-clinical-risk-management-its-application-in-the-manufacture-of-health-it-systems) and [DCB0160](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0160-clinical-risk-management-its-application-in-the-deployment-and-use-of-health-it-systems) is mandatory under the Health and Social Care Act 2012 ([Clinical risk management standards - NHS Digital](https://digital.nhs.uk/services/clinical-safety/clinical-risk-management-standards)).\n\n### Clinical safety guidance \nThe [Guide for Access Record: Structured](https://github.com/nhsconnect/gpc-consumer-support/blob/master/Clinical%20Safety%20Officer%20Guidance%20for%20GP%20Connect%20V0.6%20Structured.pdf) helps clinical safety officers assure GP Connect consumer systems into their own organisations. It includes details of the clinical safety standards that consumer suppliers and their commissioning organisations must be compliant with ([DCB0129](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0129-clinical-risk-management-its-application-in-the-manufacture-of-health-it-systems) and [DCB0160](https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0160-clinical-risk-management-its-application-in-the-deployment-and-use-of-health-it-systems)).\n\n[Clinical safety principles](https://github.com/nhsconnect/gpc-consumer-support/wiki/Clinical-Safety-Principles) shows you who is responsible for the clinical safety of GP Connect specifications and consumer systems.\n\n### Hazard log\nThe GP Connect Access Record: Structured generic [hazard log](http://github.com/nhsconnect/gpc-consumer-support/raw/master/test_data_files/GP_Connect_Hazard_Log_Consumers_v1.0.xlsx) shows you the clinical risks of using GP Connect functionality through a consumer system. Use it to identify the clinical risks of consuming clinical data and presenting it in your system, and record these in your own system-specific hazard log. If necessary, take mitigating action to ensure clinical safety.\n  \n"
  contact:
    name: gp-connect-access-record-structured-fhir API Support
    url: https://simplifier.net/guide/gp-connect-access-record-structured/Home/Help-and-Support/Enquiries.page.md?version=current
    email: gpconnect@nhs.net
tags:
- name: Documents
paths:
  /documents/Patient/{id}:
    get:
      operationId: get-document-patient
      summary: Find a patient by NHS number on the Access Document FHIR server
      description: 'Use this endpoint to find a Patient.


        If searching for a Patient''s document this endpoint must be used to obtain the correct patient id from the provider system.


        No request body is required for this endpoint.

        '
      parameters:
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - in: path
        name: id
        description: The NHS Number of the patient you are searching for.
        schema:
          type: string
          example: 9000000009
        required: true
      responses:
        '200':
          description: 'This endpoint returns a Patient resource.

            '
          content:
            application/fhir+json:
              schema:
                type: object
                description: The response will be a populated Patient resource.
              example:
                resourceType: Bundle
                type: searchset
                entry:
                - resource:
                    resourceType: Patient
                    id: '2'
                    meta:
                      versionId: '1469448000000'
                      profile:
                      - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1
                    extension:
                    - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-RegistrationDetails-1
                      extension:
                      - url: preferredBranchSurgery
                        valueReference:
                          reference: Location/785b4ff5-aced-4bdf-b7ed-34f92131ce97
                    - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NHSCommunication-1
                      extension:
                      - url: language
                        valueCodeableConcept:
                          coding:
                          - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-HumanLanguage-1
                            code: bn
                            display: Bengali
                      - url: interpreterRequired
                        valueBoolean: false
                    identifier:
                    - extension:
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NHSNumberVerificationStatus-1
                        valueCodeableConcept:
                          coding:
                          - system: https://fhir.nhs.uk/CareConnect-NHSNumberVerificationStatus-1
                            code: '01'
                            display: Number present and verified
                      system: https://fhir.nhs.uk/Id/nhs-number
                      value: '9476719931'
                    active: true
                    name:
                    - use: official
                      text: JACKSON Jane (Miss)
                      family: Jackson
                      given:
                      - Jane
                      prefix:
                      - Miss
                    telecom:
                    - system: phone
                      value: 01454587554
                      use: home
                    gender: female
                    birthDate: '1952-05-31'
                    address:
                    - use: home
                      type: physical
                      line:
                      - Trevelyan Square
                      - Boar Ln
                      city: Leeds
                      district: West Yorkshire
                      postalCode: LS1 6AE
                    managingOrganization:
                      reference: Organization/14
        4XX:
          description: 'An error occured as follows:



            | HTTP Status | Spine error code   | Description                                                                             |

            | ----------- | ----------------   | -----------                                                                             |

            | 422         | INVALID_PARAMETER  | The identifier parameter is not provided                                                |

            | 422         | INVALID_PARAMETER  | The identifier parameter contains a missing or unrecognised system                      |

            | 400         | INVALID_NHS_NUMBER | The NHS number provided is invalid, for example it fails format or check digit tests    |

            '
          content:
            application/fhir+json:
              schema:
                type: object
                description: Link to GPConnect-OperationOutcome-1 resource population guidance [here](https://simplifier.net/guide/gpconnect-data-model/Home/FHIR-Assets/All-assets/Profiles/Profile--GPConnect-OperationOutcome-1?version=current).
              examples:
                example:
                  value:
                    resourceType: OperationOutcome
                    meta:
                      profile:
                      - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-OperationOutcome-1
                    issue:
                    - severity: error
                      code: value
                      details:
                        coding:
                        - system: https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1
                          code: INVALID_NHS_NUMBER
                          display: Invalid NHS Number
      tags:
      - Documents
  /documents/Binary/{id}:
    get:
      operationId: get-document
      summary: Get a specific document from a GP practice
      description: 'Use this endpoint to retrieve a specific document using the id.  The NHS number of the patient is also required as a query string parameter. No request body is required for this endpoint.

        '
      parameters:
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - in: path
        name: id
        description: The id of the document you are searching for.
        schema:
          type: string
          example: 07a6483f-732b-461e-86b6-edb665c45510
        required: true
      - in: query
        name: patientNHSNumber
        description: The NHS number of the patient to whom the document belongs.
        required: true
        schema:
          type: string
          example: '9000000009'
      responses:
        '200':
          description: 'A successful response to retrieve a document. This will return a document in encoded base 64.

            '
          content:
            application/fhir+json:
              schema:
                type: object
                description: The response will be a populated Binary resource.
              example:
                resourceType: Binary
                id: 07a6483f-732b-461e-86b6-edb665c45510
                contentType: application/msword
                content: UEsDBBQABgAIAAAAIQDfpNJsWgEAACAFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0lMtuwjAQRfeV+g+Rt1Vi6KKqKgKLPpYtUukHGHsCVv2Sx7z+vhMCUVUBkQpsIiUz994zVsaD0dqabAkRtXcl6xc9loGTXmk3K9nX5C1/ZBkm4ZQw3kHJNoBsNLy9GUw2ATAjtcOSzVMKT5yjnIMVWPgAjiqVj1Ykeo0zHoT8FjPg973eA5feJXApT7UHGw5eoBILk7LXNX1uSCIYZNlz01hnlUyEYLQUiep86dSflHyXUJBy24NzHfCOGhg/mFBXjgfsdB90NFEryMYipndhqYuvfFRcebmwpCxO2xzg9FWlJbT62i1ELwGRztyaoq1Yod2e/ygHpo0BvDxF49sdDymR4BoAO+dOhBVMP69G8cu8E6Si3ImYGrg8RmvdCZFoA6F59s/m2NqciqTOcfQBaaPjP8ber2ytzmngADHp039dm0jWZ88H9W2gQB3I5tv7bfgDAAD//wMAUEsDBBQABgAIAAAAIQAekRq37wAAAE4CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLBasMwDEDvg/2D0b1R2sEYo04vY9DbGNkHCFtJTBPb2GrX/v082NgCXelhR8vS05PQenOcRnXglF3wGpZVDYq9Cdb5XsNb+7x4AJWFvKUxeNZw4gyb5vZm/cojSSnKg4tZFYrPGgaR+IiYzcAT5SpE9uWnC2kiKc/UYySzo55xVdf3mH4zoJkx1dZqSFt7B6o9Rb6GHbrOGX4KZj+xlzMtkI/C3rJdxFTqk7gyjWop9SwabDAvJZyRYqwKGvC80ep6o7+nxYmFLAmhCYkv+3xmXBJa/ueK5hk/Nu8hWbRf4W8bnF1B8wEAAP//AwBQSwMEFAAGAAgAAAAhANZks1H0AAAAMQMAABwACAF3b3JkL19yZWxzL2RvY3VtZW50LnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLLasMwEEX3hf6DmH0tO31QQuRsSiHb1v0ARR4/qCwJzfThv69ISevQYLrwcq6Yc8+ANtvPwYp3jNR7p6DIchDojK971yp4qR6v7kEQa1dr6x0qGJFgW15ebJ7Qak5L1PWBRKI4UtAxh7WUZDocNGU+oEsvjY+D5jTGVgZtXnWLcpXndzJOGVCeMMWuVhB39TWIagz4H7Zvmt7ggzdvAzo+UyE/cP+MzOk4SlgdW2QFkzBLRJDnRVZLitAfi2Myp1AsqsCjxanAYZ6rv12yntMu/rYfxu+wmHO4WdKh8Y4rvbcTj5/oKCFPPnr5BQAA//8DAFBLAwQUAAYACAAAACEAU5rl1tsCAABgCgAAEQAAAHdvcmQvZG9jdW1lbnQueG1spJZLb9swDIDvA/YfDN9b+ZVHjSYFmmZFDwOKZTsPiqzERqwHJCVp9utHyXacwWvhuD44lkh+IiWS0f3DGyu9A1W6EHzmh7eB71FORFbw7cz/9fPbzdT3tME8w6XgdOafqPYf5l+/3B/TTJA9o9x4gOA6PUoy83NjZIqQJjllWN+ygiihxcbcEsGQ2GwKQtFRqAxFQRi4L6kEoVrDegvMD1j7NY689aNlCh/B2AITRHKsDH1rGeHVkBG6Q9MuKBoAggijsIuKr0aNkfWqA0oGgcCrDmk0jPSf4MbDSFGXNBlGiruk6TBSJ51YN8GFpByEG6EYNjBUW8Sw2u3lDYAlNsW6KAtzAmYwbjC44LsBHoHVmcDi7GrCBDGR0TLOGoqY+XvF09r+5mxvXU8r+/qnsVB94q9Mnurm4CJHipawF4LrvJDnCmdDaSDMG8jhoyAOrGz0jjLsWS7vtaenaitbYB/36/1nZeX5x8Qw6HEiFnG26OPCv2s2njDIwnbhQVtzsblhzwbSAKIOYEyKnindMKrdhHjA8oKj6XWYUYPRJ9aW+lFuP5ctz0rsZUsrPkd7aWv/aP+Fr2DVWXdZCfpzzqxyLKElMJK+bLlQeF2CR5BDHqSB507AvuFUPFt0/hyuCmuRneyvBEmSSqzwC5z2eBGNkrtl7LtZaLTGzk7qB2ZTuJZkP2Z+EATLeJFMz1NPdIP3pbGSyTieLgO3irIvdx1JtcQEvJKKaqoO1J971XOPQGNu3055LcTO9uuVgUYPcJuDgV2FYwbmv5/FIyY7H13qLnl21kQOJa1YU2Je1fs+r0BuZx8fo0UUOn/ldvUHpFDFYXgXuHVz+B5PE0e2Ct+xRRoBzSZMEqeiim1u2uFaGCNYOy7p5kKaU5xRaNuTwDmyEcJcDLd744b1ckSUGmbrvbM6bhruec/KnmZaFpy+FoaAl/G4ib4K3H1Wx4zaq+H8LwAAAP//AwBQSwMEFAAGAAgAAAAhALb0Z5jSBgAAySAAABUAAAB3b3JkL3RoZW1lL3RoZW1lMS54bWzsWUuLG0cQvgfyH4a5y3rN6GGsNdJI8mvXNt61g4+9UmumrZ5p0d3atTCGYJ9yCQSckEMMueUQQgwxxOSSH2OwSZwfkeoeSTMt9cSPXYMJu4JVP76q/rqquro0c+Hi/Zg6R5gLwpKOWz1XcR2cjNiYJGHHvX0wLLVcR0iUjBFlCe64Cyzcizuff3YBnZcRjrED8ok4jzpuJOXsfLksRjCMxDk2wwnMTRiPkYQuD8tjjo5Bb0zLtUqlUY4RSVwnQTGovTGZkBF2DpRKd2elfEDhXyKFGhhRvq9UY0NCY8fTqvoSCxFQ7hwh2nFhnTE7PsD3petQJCRMdNyK/nPLOxfKayEqC2RzckP9t5RbCoynNS3Hw8O1oOf5XqO71q8BVG7jBs1BY9BY69MANBrBTlMups5mLfCW2BwobVp095v9etXA5/TXt/BdX30MvAalTW8LPxwGmQ1zoLTpb+H9XrvXN/VrUNpsbOGblW7faxp4DYooSaZb6IrfqAer3a4hE0YvW+Ft3xs2a0t4hirnoiuVT2RRrMXoHuNDAGjnIkkSRy5meIJGgAsQJYecOLskjCDwZihhAoYrtcqwUof/6uPplvYoOo9RTjodGomtIcXHESNOZrLjXgWtbg7y6sWLl4+ev3z0+8vHj18++nW59rbcZZSEebk3P33zz9Mvnb9/+/HNk2/teJHHv/7lq9d//Plf6qVB67tnr58/e/X913/9/MQC73J0mIcfkBgL5zo+dm6xGDZoWQAf8veTOIgQyUt0k1CgBCkZC3ogIwN9fYEosuB62LTjHQ7pwga8NL9nEN6P+FwSC/BaFBvAPcZoj3Hrnq6ptfJWmCehfXE+z+NuIXRkWzvY8PJgPoO4JzaVQYQNmjcpuByFOMHSUXNsirFF7C4hhl33yIgzwSbSuUucHiJWkxyQQyOaMqHLJAa/LGwEwd+GbfbuOD1Gber7+MhEwtlA1KYSU8OMl9BcotjKGMU0j9xFMrKR3F/wkWFwIcHTIabMGYyxEDaZG3xh0L0Gacbu9j26iE0kl2RqQ+4ixvLIPpsGEYpnVs4kifLYK2IKIYqcm0xaSTDzhKg++AElhe6+Q7Dh7ref7duQhuwBombm3HYkMDPP44JOELYp7/LYSLFdTqzR0ZuHRmjvYkzRMRpj7Ny+YsOzmWHzjPTVCLLKZWyzzVVkxqrqJ1hAraSKG4tjiTBCdh+HrIDP3mIj8SxQEiNepPn61AyZAVx1sTVe6WhqpFLC1aG1k7ghYmN/hVpvRsgIK9UX9nhdcMN/73LGQObeB8jg95aBxP7OtjlA1FggC5gDBFWGLd2CiOH+TEQdJy02t8pNzEObuaG8UfTEJHlrBbRR+/gfr/aBCuPVD08t2NOpd+zAk1Q6Rclks74pwm1WNQHjY/LpFzV9NE9uYrhHLNCzmuaspvnf1zRF5/mskjmrZM4qGbvIR6hksuJFPwJaPejRWuLCpz4TQum+XFC8K3TZI+Dsj4cwqDtaaP2QaRZBc7mcgQs50m2HM/kFkdF+hGawTFWvEIql6lA4MyagcNLDVt1qgs7jPTZOR6vV1XNNEEAyG4fCazUOZZpMRxvN7AHeWr3uhfpB64qAkn0fErnFTBJ1C4nmavAtJPTOToVF28KipdQXstBfS6/A5eQg9Ujc91JGEG4Q0mPlp1R+5d1T93SRMc1t1yzbayuup+Npg0Qu3EwSuTCM4PLYHD5lX7czlxr0lCm2aTRbH8PXKols5AaamD3nGM5c3Qc1IzTruBP4yQTNeAb6hMpUiIZJxx3JpaE/JLPMuJB9JKIUpqfS/cdEYu5QEkOs591Ak4xbtdZUe/xEybUrn57l9FfeyXgywSNZMJJ1YS5VYp09IVh12BxI70fjY+eQzvktBIbym1VlwDERcm3NMeG54M6suJGulkfReN+SHVFEZxFa3ij5ZJ7CdXtNJ7cPzXRzV2Z/uZnDUDnpxLfu24XURC5pFlwg6ta054+Pd8nnWGV532CVpu7NXNde5bqiW+LkF0KOWraYQU0xtlDLRk1qp1gQ5JZbh2bRHXHat8Fm1KoLYlVX6t7Wi212eA8ivw/V6pxKoanCrxaOgtUryTQT6NFVdrkvnTknHfdBxe96Qc0PSpWWPyh5da9Savndeqnr+/XqwK9W+r3aQzCKjOKqn649hB/7dLF8b6/Ht97dx6tS+9yIxWWm6+CyFtbv7qu14nf3DgHLPGjUhu16u9cotevdYcnr91qldtDolfqNoNkf9gO/1R4+dJ0jDfa69cBrDFqlRjUISl6joui32qWmV6t1vWa3NfC6D5e2hp2vvlfm1bx2/gUAAP//AwBQSwMEFAAGAAgAAAAhAIjo7O69AwAAZgoAABEAAAB3b3JkL3NldHRpbmdzLnhtbLRW227bOBB9X2D/wdDzKrpYshOhTuFL3aSIt4vKi32mJMomwotAUnHdYv99h5RouZtu4WyRl4SaM3NmODxD+s3bz4yOnrBURPCZF12F3gjzUlSE72ben9u1f+2NlEa8QlRwPPOOWHlvb3/95c0hU1hrcFMjoOAqY+XM22vdZEGgyj1mSF2JBnMAayEZ0vApdwFD8rFt/FKwBmlSEEr0MYjDcOL1NGLmtZJnPYXPSCmFErU2IZmoa1Li/p+LkJfk7UJWomwZ5tpmDCSmUIPgak8a5djY/2UDcO9Inn60iSdGnd8hCi/Y7kHI6hRxSXkmoJGixErBATHqCiR8SJw8IzrlvoLc/RYtFYRHoV2dV56+jCB+RjApSfUyjknPEUDkGY/CL6NJHY06MvzZESl6SWs76IEUEslOuH1fWZnd77iQqKBQDvR3BC0a2erMX1PxLQzNFyHY6JA1WJagHJi49NoLDADnJepcIw3u2U4iBpMy80qKEe8cKlyjluotKnItGnB6QlDxNA47uNwjiUqNZd6gEk59KbiWgjq/Svwu9BKmToIo+gg7g8Mq7+YZIjhisIdvZnQjKhi4Q9ZKcnmzTYDNHqXnKf+dSMD9I0mFt6Z3uT5SvIbic/IFz3n1oVWaAKOd1J+o4EcFYG4yf4TT3h4bvMZIt9CmV0pmT2JNSbMhUgp5zysQwqslI3WNJSQgIKwNyIdIcbB9vsOogmv/lfK2Cv8FzjBs4y3I8nEhtBbs7tjsodc/d5JW78G5fOHxqpRbfBJCn1zD6WR8/a6fEIMOSPhuvEz62fsW+e+Y6TxZhN+NWSziZWw7EpzqYZl5Ev6QbmVEPWJdxBKxQhI02phHIzAehXxcEO7wAsOlg8+RvC0c6PsdoBiidA3tdYAtmmUVUc0K13ZNN0juBt7eQ37XCjfMhxOXuZ6wfC9F23ToQaKmE6tziZKkjyRcPxDm7KotchfF4Zo8g1pefXyStk9Dew6ZhsO3Q/+ArIisL+b++0UvMipzIxC8QU3T6azYRTOPkt1eR0YaGr4q+G1hP4pd3GOxxeIOsx+oNDsD734x2GJnO/MbO9t4sCXOlgy21NnSwTZxtomx7eFmkZTwR5C8Wxp7LSgVB1zdDfgzk3sASgInnh9ZMdzrVx1GiYIZbOAJ0EI67DeLRUlWifIexAqr/s1YJely2Q1wlNqnQ9sxhdZ+wvUCKVz1mAtNu9Cv1/PFzXwd3/jxfLn0ozhZ+DfTVeRPx+l8vkrGq3E4+bufA/cD8fYfAAAA//8DAFBLAwQUAAYACAAAACEAzAU54nABAAD3AgAAEQAIAWRvY1Byb3BzL2NvcmUueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnJJRT4MwEMffTfwOpO9Q2MyiBFiiZk8uMdmMxrfa3kYdlKa9je3bW2AwiXvy7a73u/9d/20yP5aFdwBjZaVSEgUh8UDxSki1TcnbeuHfE88iU4IVlYKUnMCSeXZ7k3Ad88rAq6k0GJRgPaekbMx1SnJEHVNqeQ4ls4EjlCtuKlMydKnZUs34jm2BTsJwRktAJhgy2gj6elAkZ0nBB0m9N0UrIDiFAkpQaGkURPTCIpjSXm1oK7/IUuJJw1W0Lw700coBrOs6qKct6vaP6MfyZdVe1Zeq8YoDyRLBY5RYQJbQS+giu//6Bo7d8ZC4mBtgWJlsyRBzqL0Vgs5B2Rbsi43tOzjVlRHWSYwyhwmw3EiN7jG7AaMDRxfM4tK97kaCeDxdmfWXadoMHGTzQ7KoJYY0Odvd7QfCczbFnal95X369LxekGwSRg9++OBPZusojKO7OAw/mxVH/RfB8rzAvxV7gc6l8VfNfgAAAP//AwBQSwMEFAAGAAgAAAAhABuSEMjFAQAAiwUAABIAAAB3b3JkL2ZvbnRUYWJsZS54bWzcktuK2zAQhu8LfQeh+41lJ85uzTpLDxsolF4s2wdQFNkW1cFolHjz9h3JTloaFtY3vagNQvpn5hvpZ+4fXowmR+lBOVvTfMEokVa4vbJtTX88b2/uKIHA7Z5rZ2VNTxLow+b9u/uhapwNQLDeQmVETbsQ+irLQHTScFi4XloMNs4bHvDo28xw//PQ3whneh7UTmkVTlnB2JpOGP8WimsaJeQXJw5G2pDqMy81Ep2FTvVwpg1voQ3O73vvhATANxs98gxX9oLJV1cgo4R34JqwwMdMN0ooLM9Z2hn9G1DOAxRXgLVQ+3mM9cTIsPIPDsh5mPKMgZORL5QYUX1trfN8p5GE1hB8HUnguMZmm2k2yFBZbjDrM9dq51UK9Nw6kDnGjlzXlBVsy0pc479iy7jSLCaKjnuQETImslFuuFH6dFZhUABjoFdBdGf9yL2KNxxDoFoMHGDHavrIGCs+brd0VHK8XVRWt58mpYi90vdhUpYXhUVFJE465iNHJM4lB3tmowNXTjwrI4F8lwN5cobbVxwp2BqdKNGP6MxyliM+cWc78vi3I7d35T9xZJoN8k21XXh1QuJc/KcTMm1g8wsAAP//AwBQSwMEFAAGAAgAAAAhAL3Ujb8nAQAAjwIAABQAAAB3b3JkL3dlYlNldHRpbmdzLnhtbJTSzWoCMRAA4Huh7xBy16xSpSyuQimWXkqh7QPE7KyGZjIhE7vap2/can/w4l5CJsl8yYSZLXboxAdEtuQrORoWUoA3VFu/ruTb63JwKwUn7WvtyEMl98ByMb++mrVlC6sXSCmfZJEVzyWaSm5SCqVSbDaAmocUwOfNhiLqlMO4Vqjj+zYMDGHQya6ss2mvxkUxlUcmXqJQ01gD92S2CD51+SqCyyJ53tjAJ629RGsp1iGSAeZcD7pvD7X1P8zo5gxCayIxNWmYizm+qKNy+qjoZuh+gUk/YHwGTI2t+xnTo6Fy5h+HoR8zOTG8R9hJgaZ8XHuKeuWylL9G5OpEBx/Gw2Xz3CEUkkX7CUuKd5FahqgOy9o5ap+fHnKg/rXR/AsAAP//AwBQSwMEFAAGAAgAAAAhAJC8vaU6CwAANnEAAA8AAAB3b3JkL3N0eWxlcy54bWy8nU1z2zgShu9btf+BpdPuIZG/nbjGmbIde+waO+MZ2ZszREIS1iChBSl/7K9fAKQkyk1QbLDXl8Si1A9AdL8NNEhRv/z6msrometcqOx0sPt5ZxDxLFaJyKang8eHq09fBlFesCxhUmX8dPDG88Gv3/7+t19eTvLiTfI8MoAsP0nj08GsKOYnw2Eez3jK8s9qzjPz5kTplBXmpZ4OU6afFvNPsUrnrBBjIUXxNtzb2TkaVBjdhaImExHz7ypepDwrnP1Qc2mIKstnYp4vaS9daC9KJ3OtYp7n5qRTWfJSJrIVZvcAgFIRa5WrSfHZnEzVI4cy5rs77q9UrgGHOMAeABzFIsExjirG0FjWODnHYQ6XmPwt5a+DKI1PbqaZ0mwsDckMTWTOLnJg+69t7JsJjkTF3/mELWSR25f6Xlcvq1fuvyuVFXn0csLyWIgH0xlDTIWBX59luRiYdzjLi7NcsMY3Z/aPxnfivKgdPheJGAxti/l/zZvPTJ4O9g6WRy5sDzaOSZZNl8d49um383pP3KHHkT00NtzTAdOfRmfWcFidWPl/7XTnq1flp96NjQlcE8ajUk3mXT65VfETT0aFeeN0sGObMgcfb+61UNoo5nTw9Wt1cMRTcS2ShGe1D2YzkfCfM5495jxZH//zykV9dSBWi8z8vX987Pwl8+TyNeZzqyHzbsbs6P2wBtJ+eiHWjTvz/yxhu9WYNdnPOLOJJNp9j3DdRyH2rEVeO9tm5uLdubtPoRra/6iGDj6qocOPaujooxo6/qiGvnxUQw7z/2xIZAl/LYUImwHUbRyPGtEcj9jQHI+W0ByPVNAcjxLQHE+gozmeOEZzPGGK4BQq9kVhLdj3PdHezt0+R4Rxt08JYdztM0AYd3vCD+Nuz+9h3O3pPIy7PXuHcbcnazy3XGpFN0ZmWdFbZROlikwVPCr4a38aywzLVVc0PDvpcU1ykgSYMrNVE3FvWszc6+0R4kQaPp8Xtv6K1CSaiOlCm6K8b8d59sylKY8jliSGRwjUvFhoz4iExLTmE655FnPKwKaDSpHxKFukY4LYnLMpGYtnCfHwLYkkSWEV0GxRzKxIBEFQpyzWqn/XFCPLD7ci7z9WFhKdL6TkRKwfNCHmWP1rA4fpXxo4TP/KwGH6FwY1n1ENUUUjGqmKRjRgFY1o3Mr4pBq3ikY0bhWNaNwqWv9xexCFdCm+vurY7b53dyGV3Q/v3Y+RmGbMLAD6TzfVnml0zzSbajafRXb/uBlbP2dsO+cqeYseKOa0FYlqXe9C5MKctcgW/Qd0g0YlrhWPSF4rHpHAVrz+Erszy2S7QLumqWdGi3HRKFpH6iTaEZOLckHbX22s6B9hawFcCZ2TyaAZSxDBP+xy1rqTIvOte9m/Y2tWf1m9z0qk3auQBL2UKn6iScPXb3OuTVn21Jt0paRULzyhI44KrcpYq0t+z7mkk+Qv0/mM5cLVShuI7lP98kp6dMfmvU/oXjKR0fjt8lPKhIzoVhDXD3e30YOa2zLTDgwN8FwVhUrJmNVO4D9+8vE/aTp4Zorg7I3obM+Itocc7EIQTDIlSSVEJLPMFJkgmUMd73f+NlZMJzS0e83Lm1cKTkQcsXReLjoItGXy4ovJPwSrIcf7F9PC7gv1ptV2+vLF+N887p+dfqiIZDPnj0Xhtgzd6tRZ0+H6z+wbuP6z+oPb5RsJG3IEJ7uB63+yGziqk72QLM+F96pnMI/qdJc86vPtX69VPCWVniwk3QAugWQjuASSDaGSizTLKc/Y8QhP2PGoz5cwZByPYBfN8X7TIiFzhoNRecLBqNzgYFQ+cDBSB/S/qaYG639nTQ3W//aaEka0BKjBqOKMdPonujBTg1HFmYNRxZmDUcWZg1HF2f73iE8mZhFMN8XUkFQxV0PSTTRZwdO50ky/ESEvJZ8ygj3Nknav1cR+EUFl5X3XBEi7rSwJF9sljsrJP/mYrGuWRbCXyaRUimgLaz1JOMvNW8T8ZveSxXymZMK1px9+W1OXjuYsrnawwZWwTjuCt2I6K6LRbLURXscc7Wy1XBbGG2bbG2wap6O9FrM7nohFuuwo/J7B0X53Yxc5G8bLr4O0GK9n7A3Lw46WsM2j7Zbr1eiG5XFHS9jml46WLgtvWLbF8HemnxoD4bgtfla1lCf4jtuiaGXc2GxbIK0sm0LwuC2KNqQSncWx3UiH3ummGb99N/H47TEq8lMwcvJTOuvKj2gT2F/8WdgZFJM0XXurGwtArnaL1U6Z88+FKre0N67FdP++041ZoGQ5jxo5+92v6WxkGf84dk43fkTnvONHdE5AfkSnTOQ1R6UkP6VzbvIjOicpPwKdreCMgMtW0B6XraB9SLaClJBs1WMV4Ed0Xg74EWihQgRaqD1WCn4ESqjAPEiokIIWKkSghQoRaKHCBRhOqNAeJ1RoHyJUSAkRKqSghQoRaKFCBFqoEIEWKkSghRq4tveaBwkVUtBChQi0UCECLVS3XuwhVGiPEyq0DxEqpIQIFVLQQoUItFAhAi1UiEALFSLQQoUIlFCBeZBQIQUtVIhACxUi0EItv4UXLlRojxMqtA8RKqSECBVS0EKFCLRQIQItVIhACxUi0EKFCJRQgXmQUCEFLVSIQAsVItBCdRfleggV2uOECu1DhAopIUKFFLRQIQItVIhACxUi0EKFCLRQIQIlVGAeJFRIQQsVItBChYi2+KwuBfruQN/F73p6b2bvfumq6tRf9W8511H73VHLXvlZ3W/TP1fqKWr8Tt6+qze6QcRYCuW2qD2Xr+tcd+sB6mLlHxftX36p03s+j6j6moC7PArgB10twZ7KQVvI1y1BkXfQFul1S7DqPGjLvnVLMA0etCVdp8vlzR9mOgLGbWmmZrzrMW/L1jVzOMRtObpmCEe4LTPXDOEAt+XjmuFhZJPze+vDjuN0tLqPExDawrFGOPYT2sIS+mqZjqEwujrNT+jqPT+hqxv9BJQ/vRi8Y/0otIf9qDBXQ5lhXR0uVD8B62pICHI1wIS7GqKCXQ1RYa6GiRHrakjAujo8OfsJQa4GmHBXQ1SwqyEqzNVwKsO6GhKwroYErKt7TsheTLirISrY1RAV5mq4uMO6GhKwroYErKshIcjVABPuaogKdjVEhbkaVMloV0MC1tWQgHU1JAS5GmDCXQ1Rwa6GqDZXu12UDVejPFwzxy3Caoa4CblmiEvONcOAaqlmHVgt1QiB1RL01dLnuGqp7jQ/oav3/ISubvQTUP70YvCO9aPQHvajwlyNq5aaXB0uVD8B62pcteR1Na5aanU1rlpqdTWuWvK7GlctNbkaVy01uTo8OfsJQa7GVUutrsZVS62uxlVLflfjqqUmV+OqpSZX46qlJlf3nJC9mHBX46qlVlfjqiW/q3HVUpOrcdVSk6tx1VKTq3HVktfVuGqp1dW4aqnV1bhqye9qXLXU5GpctdTkaly11ORqXLXkdTWuWmp1Na5aanU1rlq6MyaC4OlIo5TpIqJ7lNo1y2cF6//cvsdM81zJZ55EtKd6S/LAuBUqutRa6e7A4cvGT03ZFtxPuJnPF8YJ9mnjte8/JeXTViug++BNsvpJKGts+xNVP5NVHXbdrq7/li06Q9hUPDNtxdVzojxNVc97XX0ryz3t9X3DnofCuo6sI3r56Wpg1+NVfm5jtFr7XVgFtfTZKax1jEoR+jr4tcoq23po+jOW5a+omT9ussQAXqqf5ip7mryyEmXev+BS3rHy02ru/6jkk6J8d3fHPWvg3fvj8kl3Xnvt8r4XMNzsTPmy+sU0z3iXz76vbkjwhqRNbg3D7e6O6TvS674t/8q//Q8AAP//AwBQSwMEFAAGAAgAAAAhANVwjr5sAQAAxQIAABAACAFkb2NQcm9wcy9hcHAueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnFLLTsMwELwj8Q9R7q1TDgVVW1eoFeLAo1JDe7bsTWLh2JbtIvr3bBoIAW74tDPrHc2ODav31mRvGKJ2dpnPpkWeoZVOaVsv85fybnKTZzEJq4RxFpf5CWO+4pcXsA3OY0gaY0YSNi7zJiW/YCzKBlsRp9S21KlcaEUiGGrmqkpL3Dh5bNEmdlUUc4bvCa1CNfGDYN4rLt7Sf0WVk52/uC9PnvQ4lNh6IxLyp27STJVLLbCBhdIlYUrdIi+IHgBsRY2Rz4D1BRxcUGfcF7BuRBAyUX78GtgIwa33RkuRKFf+qGVw0VUpez6bzbppYOMrQAvsUB6DTqfOwxjCg7a9i74gV0HUQfjm09qAYCeFwTWtzithIgL7JmDtWi8sybGhIr3X+OJLt+lS+Bz5SY5WPOjU7LyQ+GvZEQ87YlGR+8HAQMA9PUYwnTrN2hrV152/jS6+ff8r+Ww+Leic8/riaOvhu/APAAAA//8DAFBLAQItABQABgAIAAAAIQDfpNJsWgEAACAFAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhAB6RGrfvAAAATgIAAAsAAAAAAAAAAAAAAAAAkwMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhANZks1H0AAAAMQMAABwAAAAAAAAAAAAAAAAAswYAAHdvcmQvX3JlbHMvZG9jdW1lbnQueG1sLnJlbHNQSwECLQAUAAYACAAAACEAU5rl1tsCAABgCgAAEQAAAAAAAAAAAAAAAADpCAAAd29yZC9kb2N1bWVudC54bWxQSwECLQAUAAYACAAAACEAtvRnmNIGAADJIAAAFQAAAAAAAAAAAAAAAADzCwAAd29yZC90aGVtZS90aGVtZTEueG1sUEsBAi0AFAAGAAgAAAAhAIjo7O69AwAAZgoAABEAAAAAAAAAAAAAAAAA+BIAAHdvcmQvc2V0dGluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAMwFOeJwAQAA9wIAABEAAAAAAAAAAAAAAAAA5BYAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhABuSEMjFAQAAiwUAABIAAAAAAAAAAAAAAAAAixkAAHdvcmQvZm9udFRhYmxlLnhtbFBLAQItABQABgAIAAAAIQC91I2/JwEAAI8CAAAUAAAAAAAAAAAAAAAAAIAbAAB3b3JkL3dlYlNldHRpbmdzLnhtbFBLAQItABQABgAIAAAAIQCQvL2lOgsAADZxAAAPAAAAAAAAAAAAAAAAANkcAAB3b3JkL3N0eWxlcy54bWxQSwECLQAUAAYACAAAACEA1XCOvmwBAADFAgAAEAAAAAAAAAAAAAAAAABAKAAAZG9jUHJvcHMvYXBwLnhtbFBLBQYAAAAACwALAMECAADiKgAAAAA=
        4XX:
          description: 'An error occured as follows:



            | HTTP Status | Spine error code  | Description                                                                              |

            | ----------- | ----------------  | -----------                                                                              |

            | 400         | INVALID_NHS_NUMBER | The NHS number provided is invalid, for example it fails format or check digit tests    |

            | 404         | NO_RECORD_FOUND   | A document could not be found with the document id provided                              |

            | 404         | NO_RECORD_FOUND   | The document could not be retrieved due to it exceeding the file size limit              |

            | 422         | INVALID_PARAMETER  | The patientNHSNumber parameter is not provided                                          |

            '
          content:
            application/fhir+json:
              schema:
                type: object
                description: Link to GPConnect-OperationOutcome-1 resource population guidance [here](https://simplifier.net/guide/gpconnect-data-model/Home/FHIR-Assets/All-assets/Profiles/Profile--GPConnect-OperationOutcome-1?version=current).
              examples:
                example:
                  value:
                    resourceType: OperationOutcome
                    meta:
                      profile:
                      - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-OperationOutcome-1
                    issue:
                    - severity: error
                      code: not-found
                      details:
                        coding:
                        - system: https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1
                          code: NO_RECORD_FOUND
                          display: No record found
      tags:
      - Documents
components:
  parameters:
    BearerAuthorization:
      in: header
      name: Authorization
      description: 'An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).

        Required in all environments except sandbox.

        '
      required: true
      schema:
        type: string
        format: ^Bearer\ [[:ascii:]]+$
        example: Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM
    RequestID:
      in: header
      name: X-Request-ID
      required: true
      description: 'A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.

        Must be a universally unique identifier (UUID) (ideally version 4).


        In the use case of accessing a patient''s record, this UUID must be used as the id of the bundle returned.


        Mirrored back in a response header.


        If you re-send a failed request, use the same value in this header.


        Required in all environments except sandbox.

        '
      schema:
        type: string
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: 'An optional ID which you can use to track transactions across multiple systems. It can have any value, but we recommend avoiding `.` characters.

        Mirrored back in a response header.

        '
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
